// types.ts

// --- 1. The API Interfaces (From your prompts) ---

export interface SpotifyTokenResponse {
  access_token: string;
  token_type: string;
  expires_in: number;
}

export interface Track {
  id: string;
  name: string;
  album: {
    name: string;
    release_date: string;
    images: {
      url: string;
      // Optional props needed for DB compatibility
      height?: number; 
      width?: number;
    }[];
  };
  artists: {
    name: string;
  }[];
}

export interface TracksList {
  tracks: {
    items: Track[];
  };
}

// Extends Track to inherit id, name, album, artists
export interface TrackDetails extends Track {
  explicit: boolean;
  duration_ms: number;
  external_urls: {
    spotify: string;
  };
}

// --- 2. The Database Interfaces (Internal Use) ---
// These ensure db.ts continues to work while satisfying the interfaces above.

export interface SpotifyArtist {
  external_urls: { spotify: string };
  href: string;
  id: string;
  name: string;
  type: "artist";
  uri: string;
}

export interface SpotifyAlbum {
  album_type: string;
  artists: SpotifyArtist[];
  external_urls: { spotify: string };
  href: string;
  id: string;
  images: { height: number; url: string; width: number }[];
  name: string;
  release_date: string;
  total_tracks: number;
  type: "album";
  uri: string;
}

// This is the full object generated by db.ts
// It implements TrackDetails so it can be returned where TrackDetails is expected
export interface SpotifyTrack extends TrackDetails {
  album: SpotifyAlbum;    // compatible with Track.album
  artists: SpotifyArtist[]; // compatible with Track.artists
  available_markets: string[];
  disc_number: number;
  external_ids: { isrc: string };
  href: string;
  popularity: number;
  preview_url: string | null;
  track_number: number;
  type: "track";
  uri: string;
  is_local: boolean;
}

export interface PagingObject<T> {
  href: string;
  items: T[];
  limit: number;
  next: string | null;
  offset: number;
  previous: string | null;
  total: number;
}

export interface SearchResponse {
  tracks: PagingObject<SpotifyTrack>;
}